#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  one_pelumi_guy-frontend
        bind *:80
        mode http
        default_backend one_pelumi_guy-backend
backend one_pelumi_guy-backend
        balance roundrobin
        server 83505-web-01 54.210.137.174:80 check
        server 83505-web-02 35.174.211.147:80 check
"
sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
