#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely.

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT


# touch "$dirpath/myscript.pid"
echo $$ >> /var/run/myscript.pid

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
