#!/usr/bin/env bash
#A bash script that prints Best school 10 times
#using a while loop and bad luck on the 4th line
#good luck on the 8th line

((i = 1))
while ((i <= 100))
do
	if ((i % 3 == 0 && i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"	
	fi
	((i++))
done
