#!/usr/bin/env bash
#A bash script that prints Best school 10 times
#using a while loop and bad luck on the 4th line
#good luck on the 8th line

((i = 0))
while ((i < 10))
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then
		echo "good luck"
	else
		echo "Best School"	
	fi
	((i++))
done
